# Generated by Django 5.0.2 on 2024-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='follow',
            new_name='follower',
        ),
    ]
